// src/app/[locale]/(dashboard)/inspections/[id]/ClientWrapper.tsx

"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { useTranslations, useLocale } from "next-intl";
import { toast } from "sonner";
import { AdminGuard } from "@/lib/client-guard";
import { Loader2 } from "lucide-react";
import { InspectionHeader } from "./InspectionHeader";
import { InspectionStats } from "./InspectionStats";
import { InspectionItemsCard } from "./InspectionItemsCard";
import type { ResultState, InspectionData } from "../types";

interface ClientWrapperProps {
  initialData: InspectionData;
  inspectionId: string;
  locale: string;
}

export function ClientWrapper({ initialData, inspectionId, locale }: ClientWrapperProps) {
  const router = useRouter();
  const isRtl = locale === "ar";
  const t = useTranslations("Inspections");

  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [inspection, setInspection] = useState(initialData);
  const [resultsState, setResultsState] = useState<Record<string, ResultState>>({});
  const [status, setStatus] = useState(initialData.status);

  useEffect(() => {
    const initialResults: Record<string, ResultState> = {};
    initialData.categories.forEach((category) => {
      category.items.forEach((item) => {
        const existingResult = item.result || null;
        if (existingResult) {
          initialResults[item.id] = {
            id: existingResult.id || item.id,
            inspectionFormItemId: item.id,
            result: existingResult.result || "na",
            notes: existingResult.notes || "",
            imageUrl: existingResult.imageUrl || "",
          };
        } else {
          initialResults[item.id] = {
            id: item.id,
            inspectionFormItemId: item.id,
            result: "na",
            notes: "",
            imageUrl: "",
          };
        }
      });
    });
    setResultsState(initialResults);
  }, [initialData]);

  const updateResult = (inspectionFormItemId: string, field: keyof ResultState, value: any) => {
    setResultsState((prev) => ({
      ...prev,
      [inspectionFormItemId]: {
        ...prev[inspectionFormItemId],
        [field]: value,
      },
    }));
  };

  const handleSave = async (closeAfterSave: boolean = false) => {
    const resultsArray = Object.values(resultsState).map((r) => ({
      inspectionFormItemId: r.inspectionFormItemId,
      result: r.result,
      notes: r.notes,
      imageUrl: r.imageUrl,
    }));

    setSaving(true);
    try {
      const newStatus = closeAfterSave ? "completed" : status;

      const res = await fetch(`/api/inspections/${inspectionId}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          results: resultsArray,
          status: newStatus,
        }),
      });

      if (!res.ok) throw new Error("Save failed");

      toast.success(isRtl ? "✅ تم حفظ التغييرات" : "✅ Changes saved");

      setTimeout(() => {
        router.push(`/${locale}/inspections`);
      }, 1500);
    } catch (err) {
      toast.error(isRtl ? "❌ فشل الحفظ" : "❌ Save failed");
    } finally {
      setSaving(false);
    }
  };

  const handleComplete = () => {
    handleSave(true);
  };

  const stats = {
    total: Object.values(resultsState).length,
    pass: Object.values(resultsState).filter((r) => r.result === "pass").length,
    fail: Object.values(resultsState).filter((r) => r.result === "fail").length,
    na: Object.values(resultsState).filter((r) => r.result === "na").length,
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="h-8 w-8 animate-spin text-indigo-500" />
      </div>
    );
  }

  return (
    <AdminGuard>
      <div className="relative space-y-8 p-6">
        <div className="absolute inset-0 bg-gradient-to-br from-indigo-100/20 via-transparent to-purple-100/20 dark:from-indigo-950/10 dark:via-transparent dark:to-purple-950/10 rounded-3xl -z-10" />

        <InspectionHeader
          title={inspection.title}
          locationName={inspection.locationName}
          scheduledDate={inspection.scheduledDate}
          status={status}
          isRtl={isRtl}
          onSave={() => handleSave(false)}
          onComplete={handleComplete}
          isSaving={saving}
          hasFailures={stats.fail > 0}
          inspectionId={inspectionId}
          locale={locale}
        />

        <InspectionStats stats={stats} isRtl={isRtl} />

        <InspectionItemsCard
          categories={inspection.categories}
          resultsState={resultsState}
          onUpdateResult={updateResult}
          isRtl={isRtl}
        />

        <div className="print-footer hidden print:block text-center text-xs text-gray-600 mt-10 pt-4 border-t border-gray-300">
          {isRtl ? "تم الإنشاء بواسطة نظام الفحص" : "Generated by Inspection System"}
          <br />
          {new Date().toLocaleDateString(isRtl ? "ar" : "en", {
            year: "numeric",
            month: "long",
            day: "numeric",
          })}
        </div>
      </div>
    </AdminGuard>
  );
}